config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'welcome#home'
  get 'contact', to: 'welcome#contact'

  resources :books

  #appropriate resource paths for authors create_table

  get 'authors/new', to: 'authors#new'
  get 'authors', to: 'authors#index'
  post 'authors', to: 'authors#create'
  delete 'authors.:id', to: 'authors#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book
  validates :name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :set_default
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :validatable

  #Only make the first user admin
  def set_default
    if User.count == 0
      self.admin = true
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
before_action :require_admin
private
    def params_hash
      params.require(:author).permit(:name)
    end

#    def require_admin
#      if !current_user || !current_user.admin?
#        flash[:danger] = "Not permitted"
#        redirect_to root_path
#      end
#    end

public
  def new
    @author= Author.new
  end

  def create
    @author = Author.new(params_hash)
    if @author.save
      flash[:success] = "Author successfully added"
      redirect_to authors_path
    else
      render 'new'
    end
  end

  def index
    @allAuthors = Author.all
  end

  def destroy
    @author = Author.find(params[:id])
    if @author.present?
        @author.destroy
    end
    flash[:danger] = "Author deleted"
    redirect_to authors_path
  end




end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  before_action :findByID, only: [:show, :edit, :update, :delete]
private
  def params_hash
    params.require(:book).permit(:name, :author_id,:description)
  end

  def findByID
    @book = Book.find(params[:id])
  end
public
  def new
    @book = Book.new
  end

  def index
    @author = Author.all
    @allBooks = Book.all
  end

  def create
    @book = Book.new(params_hash)
    if @book.save
      flash[:success] = "The book was successfully added to your collection"
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def show
    @author = Author.all
  end

  def edit

  end

  def update
    if @book.update(params_hash)
      flash[:success] = "The book information was successfully updated"
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @book= Book.find(params[:id])
    if @book.present?
        @book.destroy
    end
    flash[:danger] = "Book successfully removed from your collection"
    redirect_to books_path
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home

  end

  def contact


  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_inputForm.html.erb
<%= render 'shared/errorMSG', obj: @author%>


<div class="row">
  <div class="col-xs-12">

      <%= form_for @author, :html => {class:"form-horizontal", role: "form"} do |s| %>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= s.label :name %>
          </div>
          <div class="col-sm-6">
            <%= s.text_field :name, class:"form-control", placeholder:"Enter name of author", autofocus:true%>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-5">
            <%= s.submit class: "btn btn-primary btn-lg " %>
          </div>
        </div>
        <p>
          <div class="form-group">
            <div class="col-sm-offset-2  col-sm-4">
              <%= link_to "Back", authors_path, class: "btn btn-primary btn-lg"%>
            </div>
          </div>
        </p>
    <% end %>
  </div>
</div>

app/views/authors/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authors</title>
  </head>

  <body>

<div class="blacktext panel panel-default">
  <!-- Default panel contents -->
    <div class="panel-heading"><span style="padding-left:400px;">All Authors
          <span style="padding-left:170px;"><%= link_to "Add new author",
          authors_new_path, class: "btn btn-success" %>

    </div>
  <!-- Table -->
  <table class="table">

    <tr>
      <th>Name</th>
    </tr>
    <% @allAuthors.each do |data| %>
    <tr class ="tableallignleft">
      <td><%= data.name %>  </td>

      <td><%= link_to "Remove Author", authors_path(data), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>


  </table>

  </body>
</html>

app/views/authors/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Add New Author</title>
  </head>

  <body>

    <h1><span style="padding-left:157px;">Add author</h1>
    <%= render 'inputForm'%>

  </body>
</html>

app/views/books/_inputForm.html.erb
<%= render 'shared/errorMSG', obj: @book%>

<div class="row">
  <div class="col-xs-12">

      <%= form_for @book, :html => {class:"form-horizontal", role: "form"} do |s| %>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= s.label :name %>
          </div>
          <div class="col-sm-6">
            <%= s.text_field :name, class:"form-control", placeholder:"Enter title of book", autofocus:true%>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= s.label :author %>
          </div>
          <div class="col-sm-6">
            <%= collection_select(:book, :author_id, Author.all,:id, :name, {}, {:multiple => false})%>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= s.label :description %>
          </div>
          <div class="col-sm-6">
            <%= s.text_area :description, rows:"7",  class:"form-control",placeholder:"Enter article", autofocus:true%>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-5">
            <%= s.submit class: "btn btn-primary btn-lg " %>
          </div>
        </div>
        <p>
          <div class="form-group">
            <div class="col-sm-offset-2  col-sm-4">
              <%= link_to "Back", books_path, class: "btn btn-primary btn-lg"%>
            </div>
          </div>
        </p>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edit</title>
  </head>

  <body>
  <h1><span style="padding-left:210px;">Edit book information</h1>
    <%=render 'inputForm'%>
  </body>
</html>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books</title>
  </head>

  <body>
    <div class="col-lg-3 " >

      <div class="input-group">
        <input type="text" class="show-align form-control" placeholder="Search for...">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">Go!</button>
        </span>
      </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->

<div class="blacktext panel panel-default">
  <!-- Default panel contents -->
    <div class="panel-heading"><span style="padding-left:137px;">Books Owned By Users
          <span style="padding-left:170px;"><%= link_to "Add new book",
          new_book_path, class: "btn btn-success" %>
          <span style="padding-left:10px;"><%= link_to "View my books???", "#",
          class: "btn btn-primary"%>

    </div>
  <!-- Table -->
  <table class="table">

    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Description</th>
    </tr>
    <% @allBooks.each do |data| %>
    <tr class ="tableallignleft">
      <td><%= data.name %>  </td>
        <td><%= @author.find(data.author_id).name %>  </td>
      <td><%= data.description%>  </td>
      <td><%= link_to "Edit Info", edit_book_path(data) %></td>
      <td><%= link_to "Show Info", book_path(data) %></td>
      <td><%= link_to "Remove from collection", book_path(data), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>


  </table>

  </body>
</html>

app/views/books/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Add New Book</title>
  </head>

  <body>

    <h1><span style="padding-left:157px;">Add new book to collection</h1>
    <%= render 'inputForm'%>

  </body>
</html>

app/views/books/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Show Book</title>
  </head>

  <body>

      <h2 class = "center"><b><%= @book.name %></b></h2>
      </br>
      <div class ="blacktext well col-xs-8 col-xs-offset-2 center">
        <h4 class = "center"><strong>Author:</strong></h4>
        <hr> <%= @author.find(@book.author_id).name %>
        <h4 class = "center"><strong>Description:</strong></h4>
        <hr> <%= simple_format(@book.description) %>
        <div class="article-actions">
          <%= link_to "Edit Book", edit_book_path(@book), class: "btn btn-xs btn-primary" %>

          <%= link_to "Back",  books_path ,class: "btn btn-xs btn-success" %>
        </div>
      </div>
  </body>
</html>

app/views/layouts/_flashMSG.html.erb
<!--<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="row">
  <div class ="col-xs-8 col-xs-offset-2">
    <p class="notice"><%= notice %>
    <p class="alert"><%= alert %></p>
    </div>
</div>
-->

<div class="row">
  <div class ="col-xs-8 col-xs-offset-2">
    <% flash.each do |name, msg| %>
    <div class= 'alert alert-<%="#{name}"%>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class= "container">
  <footer class="footer-style">
    <small>
      Copyright &copy; by Shobin Sunny
    </small>

    <nav>
      <ul>
        <li><%= link_to "Contact Us", contact_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Lib Locker", root_path, class: "navbar-brand", id: "logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%=link_to "View books", books_path %></li>
        <li><a href="#">Link</a></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-default ", type: "button"%>
          <%else%>
            <%= link_to "Sign in", new_user_session_path, class: "btn btn-default", type: "button" %>
          <%end%>
          <!--<button type="button" class="btn btn-default navbar-btn">Sign in</button> -->
        </li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'  %>
    <%= render 'layouts/flashMSG'  %>

    <div class = "container">
      <%= yield %>
    </div>
  <%= render 'layouts/footer'%>
  </body>
</html>

app/views/shared/_errorMSG.html.erb
<% if obj.errors.any? %>
<div class ="row">
  <div class="col-xs-6 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count, "error")%>
          occured:
        </h2>
        <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
            <li><%=msg%>
            <% end %>

          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/welcome/contact.html.erb
<h1>Contact Us</h1>

<%= link_to 'Home', root_path%>

app/views/welcome/home.html.erb
<div class = "jumbotron center">

  <h1> Lib Locker</h1>
  <%= link_to "Sign up", new_user_registration_path , class: "btn btn-danger btn-lg btn-style"%>

</div>